server {
    listen 80;

    # 正常的網頁請求，直接讀取編譯好的 HTML/JS
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 抓到 /api 開頭的請求，轉發給後端 Python 容器
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}